### ISSUE TITLE
Windows Build Issue under MINGW / MSYS (gcc 4.8.1)

### ISSUE THREAD

**Issue by ghost** [sgminer-dev/sgminer#12]
Hello,

Configure output is below:

```
------------------------------------------------------------------------
sgminer 4.0.0
------------------------------------------------------------------------


Configuration Options Summary:

  libcurl(GBT+getwork).: Enabled: -Lc:/mingw/lib -lcurl -lcurldll
  curses.TUI...........: FOUND: -lpdcurses
  OpenCL...............: FOUND. GPU mining support enabled
  ADL..................: SDK found, GPU monitoring support enabled

Compilation............: make (or gmake)
  CPPFLAGS.............:
  CFLAGS...............: -D WIN32_LEAN_AND_MEAN
  LDFLAGS..............:
  LDADD................:  -Lc:/mingw/lib -lcurl -lcurldll   compat/jansson-2.5/src/.libs/libjansson.a -lpthread -lOpenCL   -lws2_32 -lm

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
```

GCC Version info is below:

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=c:\mingw\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.8.1/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.8.1/configure --prefix=/mingw --host=mingw32 --build=mingw32 --without-pic --enable-shared --enable-static --with-gnu-ld --enable-lto --enable-libssp --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++,ada --disable-sjlj-exceptions --with-dwarf2 --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runtime-libs --with-gmp=/usr/src/pkg/gmp-5.1.2-1-mingw32-src/bld --with-mpc=/usr/src/pkg/mpc-1.0.1-1-mingw32-src/bld --with-mpfr= --with-system-zlib --with-gnu-as --enable-decimal-float=yes --enable-libgomp --enable-threads --with-libiconv-prefix=/mingw32 --with-libintl-prefix=/mingw --disable-bootstrap LDFLAGS=-s CFLAGS=-D_USE_32BIT_TIME_T
Thread model: win32
gcc version 4.8.1 (GCC)
```

Make output is below:

```
$ make
make  all-recursive
make[1]: Entering directory `/home/Mike/sgminer-master'
Making all in lib
make[2]: Entering directory `/home/Mike/sgminer-master/lib'
  GEN    arg-nonnull.h
  GEN    c++defs.h
  GEN    warn-on-use.h
  GEN    signal.h
  GEN    string.h
make  all-recursive
make[3]: Entering directory `/home/Mike/sgminer-master/lib'
make[4]: Entering directory `/home/Mike/sgminer-master/lib'
  CC     dummy.o
  CC     memmem.o
  CC     sigaction.o
  CC     sigprocmask.o
  AR     libgnu.a
make[4]: Leaving directory `/home/Mike/sgminer-master/lib'
make[3]: Leaving directory `/home/Mike/sgminer-master/lib'
make[2]: Leaving directory `/home/Mike/sgminer-master/lib'
Making all in compat
make[2]: Entering directory `/home/Mike/sgminer-master/compat'
Making all in jansson-2.5
make[3]: Entering directory `/home/Mike/sgminer-master/compat/jansson-2.5'
make  all-recursive
make[4]: Entering directory `/home/Mike/sgminer-master/compat/jansson-2.5'
Making all in src
make[5]: Entering directory `/home/Mike/sgminer-master/compat/jansson-2.5/src'
  CC     dump.lo
  CC     error.lo
  CC     hashtable.lo
  CC     load.lo
  CC     memory.lo
  CC     pack_unpack.lo
  CC     strbuffer.lo
  CC     strconv.lo
  CC     utf.lo
  CC     value.lo
  CCLD   libjansson.la
make[5]: Leaving directory `/home/Mike/sgminer-master/compat/jansson-2.5/src'
make[5]: Entering directory `/home/Mike/sgminer-master/compat/jansson-2.5'
make[5]: Nothing to be done for `all-am'.
make[5]: Leaving directory `/home/Mike/sgminer-master/compat/jansson-2.5'
make[4]: Leaving directory `/home/Mike/sgminer-master/compat/jansson-2.5'
make[3]: Leaving directory `/home/Mike/sgminer-master/compat/jansson-2.5'
make[3]: Entering directory `/home/Mike/sgminer-master/compat'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/Mike/sgminer-master/compat'
make[2]: Leaving directory `/home/Mike/sgminer-master/compat'
Making all in ccan
make[2]: Entering directory `/home/Mike/sgminer-master/ccan'
  CC     opt/libccan_a-helpers.o
  CC     opt/libccan_a-opt.o
  CC     opt/libccan_a-parse.o
  CC     opt/libccan_a-usage.o
  AR     libccan.a
make[2]: Leaving directory `/home/Mike/sgminer-master/ccan'
make[2]: Entering directory `/home/Mike/sgminer-master'
  CC     sgminer-sgminer.o
  CC     sgminer-api.o
  CC     sgminer-util.o
  CC     sgminer-sha2.o
In file included from sha2.h:35:0,
                 from sha2.c:37:
config.h:361:0: warning: "_WIN32_WINNT" redefined [enabled by default]
 #define _WIN32_WINNT 0x0501
 ^
In file included from c:\mingw\include\_mingw.h:35:0,
                 from c:\mingw\include\string.h:29,
                 from ./lib/string.h:28,
                 from sha2.c:35:
c:\mingw\include\sdkddkver.h:154:0: note: this is the location of the previous definition
 #    define _WIN32_WINNT _WIN32_WINNT_WIN2K
 ^
  CC     sgminer-logging.o
  CC     sgminer-driver-opencl.o
  CC     sgminer-ocl.o
  CC     sgminer-findnonce.o
  CC     sgminer-adl.o
  CC     sgminer-scrypt.o
  CCLD   sgminer.exe
sgminer-sgminer.o:sgminer.c:(.text+0x11b35): undefined reference to `llround'
sgminer-sgminer.o:sgminer.c:(.text+0x1cc48): undefined reference to `timeEndPeriod'
sgminer-sgminer.o:sgminer.c:(.text+0x1ef04): undefined reference to `timeBeginPeriod'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: sgminer-sgminer.o: bad reloc address 0x0 in section `.data'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [sgminer.exe] Error 1
make[2]: Leaving directory `/home/Mike/sgminer-master'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/Mike/sgminer-master'
make: *** [all] Error 2
$
```

The windows-build.txt should be amended to include a comment about ensuring you update "/etc/fstab.sample" to "/etc/fstab", otherwise a ton of includes/libraries required for build are not present.  Also, I needed to use the "-D WIN32_LEAN_AND_MEAN" build option in order to get past a winsock/winsock2 conflict.  I can't seem to get around this issue with "llround" and "timeEndPeriod", though.
